### ISSUE TITLE
Error when executing from console

### ISSUE THREAD

**Issue by morris178** [stevecope/mqtt-data-logger#3]
Running `python3 mqtt-data-logger.py -b 192.168.178.62 -t cistern/# -s `

will fail with this output. I am running Debian Stretch
```
Traceback (most recent call last):
  File "mqtt-data-logger.py", line 16, in <module>
    import mlogger as mlogger
  File "/home/morris/mqtt-data-logger/mlogger.py", line 44
    using the timestamp for the name"""   
                                      ^
IndentationError: expected an indented block
```

**Comment by morris178** [comment]
#4 resolved the issue for me
